INSERT INTO PLAYER (USERNAME) VALUES ('ivan');

INSERT INTO WORD (NAME) VALUES ('лаптоп');
INSERT INTO WORD (NAME) VALUES ('стол');
INSERT INTO WORD (NAME) VALUES ('парк');
INSERT INTO WORD (NAME) VALUES ('информация');