INSERT INTO WORD (NAME) VALUES ('лаптоп');
INSERT INTO WORD (NAME) VALUES ('парк');
INSERT INTO WORD (NAME) VALUES ('стол');
INSERT INTO WORD (NAME) VALUES ('дума');

INSERT INTO PLAYER (USERNAME) VALUES ('stoyan');
INSERT INTO PLAYER (USERNAME) VALUES ('ivan');
INSERT INTO PLAYER (USERNAME) VALUES ('pesho');
INSERT INTO PLAYER (USERNAME) VALUES ('nikola');
