CREATE TABLE IF NOT EXISTS WORD (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PLAYER (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS HANGMAN_GAME (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  WORD_ID BIGINT NOT NULL,
  STARTED_ON_DATE DATE NOT NULL,
  CURRENT_WORD VARCHAR(100) NOT NULL,
  STATUS VARCHAR(100) NOT NULL,
  WRONG_GUESSES INT NOT NULL,
  CURRENT_WRONG_GUESS INT NOT NULL,
  PLAYER_ID BIGINT NOT NULL,

  CONSTRAINT FK_PLAYER_ID
  FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID),

  CONSTRAINT FK_WORD_ID
  FOREIGN KEY (WORD_ID) REFERENCES WORD(ID)
);

